# Generated by Django 5.1.7 on 2025-03-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demobooking',
            name='booking_time_ist',
            field=models.TimeField(editable=False, null=True),
        ),
    ]
