# Generated by Django 5.1.7 on 2025-05-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_signupuser_alter_demobooking_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.URLField(max_length=500)),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('Public Speaking', 'Public Speaking'), ('ELA', 'ELA'), ('Personalized Courses', 'Personalized Courses')], max_length=50)),
                ('grades', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_materials', to='skills.signupuser')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='skills.studymaterial')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'unique_together': {('student', 'material')},
            },
        ),
    ]
