# Generated by Django 5.1.7 on 2025-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_test_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='TheSkillsTree/skills/static/student_images/'),
        ),
    ]
