# Generated by Django 5.1.7 on 2025-06-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_signupuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, upload_to='skills/static/student_images/'),
        ),
    ]
