# Generated by Django 5.1.7 on 2025-06-16 11:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_signupuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Student profile picture', null=True, storage=django.core.files.storage.FileSystemStorage(location="/Users/iam-piyush/Documents/Veritka Ma'am/TheSkillTree/TheSkillsTree/skills/static"), upload_to='student_images/'),
        ),
    ]
