# Generated by Django 5.1.7 on 2025-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_alter_signupuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterial',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
