# Generated by Django 5.1.7 on 2025-06-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_studentmaterial_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmaterial',
            old_name='topic',
            new_name='topics',
        ),
    ]
