# Generated by Django 5.1.7 on 2025-06-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_rename_topic_studentmaterial_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmaterial',
            old_name='topics',
            new_name='topic',
        ),
    ]
