# Generated by Django 5.1.7 on 2025-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_rename_topics_studentmaterial_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
