# Generated by Django 5.1.7 on 2025-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_studymaterial_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='short_video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
