# Generated by Django 5.1.7 on 2025-06-21 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_studymaterial_short_video_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('session', 'Study Session'), ('test', 'Test/Exam'), ('meeting', 'Parent Meeting'), ('demo', 'Demo Class'), ('other', 'Other')], default='session', max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('event_date_ist', models.DateField(editable=False, null=True)),
                ('start_time_ist', models.TimeField(editable=False, null=True)),
                ('end_time_ist', models.TimeField(editable=False, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='skills.signupuser')),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
