# Generated by Django 5.1.7 on 2025-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0016_studentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevent',
            name='class_link',
            field=models.URLField(blank=True, help_text='Add Zoom/Google Meet/Class link', null=True),
        ),
    ]
