# Generated by Django 5.1.7 on 2025-06-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0017_studentevent_class_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentevent',
            name='event_type',
            field=models.CharField(choices=[('Study Session', 'Study Session'), ('Test/Practice', 'Test/Practice')], default='Study Session', max_length=20),
        ),
    ]
