# Generated by Django 5.1.7 on 2025-06-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_alter_studentevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
