# Generated by Django 5.1.7 on 2025-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0019_studymaterial_sub_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
    ]
