# Generated by Django 5.1.7 on 2025-06-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0020_test_grade_test_is_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtest',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
