# Generated by Django 5.1.7 on 2025-06-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0021_assignedtest_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtest',
            name='student_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='skills.assignedtest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.option')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'unique_together': {('assignment', 'question')},
            },
        ),
    ]
